name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Semantic Release
        uses: semantic-release/semantic-release@v16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: terraform apply -auto-approve

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: |
          VERSION=$(jq -r '.version' package.json)
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION
          gh release create $VERSION
