name: Frontend Build and Deploy to S3

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Dist
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Package.json version increase
        run: |
          cd frontend
          git config --global user.name 'mdriyazali'
          git config --global user.email 'mdriyazali254362@gmail.com'
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "Increase version of package.json "
          git push https://${{ secrets.WORKFLOW_TOKEN }}@github.com/mdriyazali/frontend.git

      - name: Push dist's files to S3 bucket
        run: |
          aws s3 cp frontend/dist/ s3://riyazali-s3-bucket/ --recursive

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
